services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: payment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d payment" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build: .
    command: alembic upgrade head
    environment:
      DATABASE_URL: postgresql+asyncpg://username:password@postgres:5432/payment
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7.4-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
  redis_data:
    driver: local
